// src/app/(legal)/terms/page.tsx

export default function TermsAndConditionsPage() {
    return (
        <>
            <h1>Terms and Conditions</h1>
            <p><strong>Effective Date:</strong> 25th July 2025</p>
            <p>
                These Terms and Conditions (&quot;Terms&quot;) govern your use of the Talxify website located at talxify.space (the &quot;Site&quot;) and the services offered by Talxify (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing or using our Site and services, you agree to be bound by these Terms. If you do not agree to these Terms, do not use our services.
            </p>

            <h2>1. User Accounts</h2>
            <p>
                To access most features of Talxify, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for all activities that occur under your account.
            </p>

            <h2>2. Subscriptions and Payment</h2>
            <p>
                Our services are billed on a subscription basis. You will be billed in advance on a recurring, periodic basis (such as monthly or yearly), depending on the subscription plan you select. All payments are non-refundable as outlined in our <a href="/refund">Refund Policy</a>.
            </p>
            
            <h2>3. Content Ownership and License</h2>
            <p>
                We respect intellectual property rights and ask you to do the same.
            </p>
            <ul>
                <li>
                    <strong>Your Content:</strong> You retain ownership of all content you submit to the services, specifically including your resume text and job descriptions (&quot;User Content&quot;). By using our services, you grant Talxify a worldwide, non-exclusive, royalty-free license to use, reproduce, and modify your User Content solely for the purpose of providing and improving our services.
                </li>
                <li>
                    <strong>Our Content:</strong> All content generated by our AI, including but not limited to interview questions, code analysis, notes, and resume feedback, is the exclusive property of Talxify (&quot;AI Content&quot;). We grant you a limited, non-exclusive, non-transferable license to use the AI Content for your personal, non-commercial career development purposes.
                </li>
            </ul>

            <h2>4. User Conduct and Restrictions</h2>
            <p>You agree not to engage in any of the following prohibited activities:</p>
            <ul>
                <li>Using the service for any illegal purpose or in violation of any local, state, national, or international law.</li>
                <li>Attempting to interfere with, compromise the system integrity or security of, or decipher any transmissions to or from the servers running the service.</li>
                <li>Reverse-engineering, decompiling, or otherwise attempting to discover the source code of any aspect of the service.</li>
                <li>Scraping, collecting, or harvesting any personally identifiable information, including account names, from the service.</li>
                <li>Engaging in any other conduct that restricts or inhibits anyone's use or enjoyment of the service, or which, as determined by us, may harm Talxify or users of the service.</li>
            </ul>
            <p>
                Violation of these rules may result in the suspension or termination of your account at our sole discretion.
            </p>
            
            <h2>5. Disclaimers</h2>
            <p>
                The services are provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. Talxify makes no warranties, express or implied, regarding the accuracy, reliability, or completeness of the AI-generated content. You acknowledge that AI-generated content may contain inaccuracies and should be used as a supplementary tool, not a substitute for professional advice.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
                To the fullest extent permitted by applicable law, in no event shall Talxify or its founder be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the service.
            </p>

            <h2>7. Governing Law</h2>
            <p>
                These Terms shall be governed by the laws of India, without regard to its conflict of law principles.
            </p>

            <h2>8. Changes to Terms</h2>
            <p>
                We reserve the right to modify these Terms at any time. We will provide notice of any material changes by posting the new Terms on the Site. Your continued use of the service after such changes constitutes your acceptance of the new Terms.
            </p>

            <h2>9. Contact Us</h2>
            <p>
                If you have any questions about these Terms, please contact Arshad at <a href="mailto:support@talxify.space">support@talxify.space</a>.
            </p>
        </>
    )
}
